-- Run this in your Supabase SQL editor: https://supabase.com/dashboard/project/gipmtahyameimrwurbdn/sql
-- Seeds truth_or_dare table with 30 truths + 30 dares

INSERT INTO truth_or_dare (id, type, content, points, is_active) VALUES
-- TRUTHS
(gen_random_uuid(), 'truth', 'What''s the most embarrassing thing you''ve done in class?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever cheated on a test? Tell us.', 10, true),
(gen_random_uuid(), 'truth', 'Who do you have a crush on right now?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the biggest lie you''ve told your parents?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever blamed someone else for something you did?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the most embarrassing song on your playlist?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever secretly liked your friend''s ex?', 10, true),
(gen_random_uuid(), 'truth', 'What''s a secret you''ve never told anyone in this group?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever pretended to be sick to skip school?', 10, true),
(gen_random_uuid(), 'truth', 'Who in this group would you swap lives with for a week?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the weirdest dream you''ve ever had?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever sent a text to the wrong person? What did it say?', 10, true),
(gen_random_uuid(), 'truth', 'What''s something you''re too embarrassed to Google?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever eavesdropped on someone''s conversation?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the most childish thing you still do?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever liked your own post from a fake account?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the longest you''ve gone without showering?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever stolen something, even something small?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the most embarrassing thing in your camera roll right now?', 10, true),
(gen_random_uuid(), 'truth', 'Who in this room do you think is the most two-faced?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever walked into a glass door?', 10, true),
(gen_random_uuid(), 'truth', 'What''s your most embarrassing autocorrect fail?', 10, true),
(gen_random_uuid(), 'truth', 'What''s something you pretend to understand but actually don''t?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever made fun of someone behind their back?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the pettiest thing you''ve ever done for revenge?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever blocked someone and then stalked their profile on another account?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the most desperate thing you''ve done to get someone''s attention?', 10, true),
(gen_random_uuid(), 'truth', 'Have you ever laughed at something you definitely shouldn''t have?', 10, true),
(gen_random_uuid(), 'truth', 'What''s a habit you have that would gross other people out?', 10, true),
(gen_random_uuid(), 'truth', 'What''s the most embarrassing thing you''ve done when you thought no one was watching?', 10, true),

-- DARES
(gen_random_uuid(), 'dare', 'Text your crush "hey I miss you" right now.', 20, true),
(gen_random_uuid(), 'dare', 'Let someone in the group post anything they want on your Instagram story.', 20, true),
(gen_random_uuid(), 'dare', 'Do your best impression of a teacher for 30 seconds.', 20, true),
(gen_random_uuid(), 'dare', 'Call a random contact and say "I know what you did last summer" then hang up.', 20, true),
(gen_random_uuid(), 'dare', 'Show everyone your most recent Google search.', 20, true),
(gen_random_uuid(), 'dare', 'Let the group scroll through your camera roll for 30 seconds.', 20, true),
(gen_random_uuid(), 'dare', 'Send a voice note to the last person you texted saying "I think about you a lot".', 20, true),
(gen_random_uuid(), 'dare', 'Do 20 push-ups without stopping.', 20, true),
(gen_random_uuid(), 'dare', 'Let someone draw anything on your arm with a pen.', 20, true),
(gen_random_uuid(), 'dare', 'Text your parents "I need to tell you something important" and wait for their reply.', 20, true),
(gen_random_uuid(), 'dare', 'Do your best dance move in front of everyone for 30 seconds.', 20, true),
(gen_random_uuid(), 'dare', 'Speak in an accent chosen by the group for the next 3 rounds.', 20, true),
(gen_random_uuid(), 'dare', 'Let the group pick a WhatsApp status for you to post right now.', 20, true),
(gen_random_uuid(), 'dare', 'Eat something spicy without making a face.', 20, true),
(gen_random_uuid(), 'dare', 'Let someone style your hair however they want.', 20, true),
(gen_random_uuid(), 'dare', 'Call a friend and tell them you''re thinking of dropping out to become a monk.', 20, true),
(gen_random_uuid(), 'dare', 'Show your most recent DM conversation on screen.', 20, true),
(gen_random_uuid(), 'dare', 'Sing the full chorus of the last song you listened to out loud.', 20, true),
(gen_random_uuid(), 'dare', 'Let the group change your phone wallpaper to whatever they want.', 20, true),
(gen_random_uuid(), 'dare', 'Try to lick your elbow for 10 seconds.', 20, true),
(gen_random_uuid(), 'dare', 'Talk like a robot for the next 2 rounds.', 20, true),
(gen_random_uuid(), 'dare', 'Do a 1-minute standup comedy routine right now.', 20, true),
(gen_random_uuid(), 'dare', 'Write a dramatic 3-line love poem about the person to your left.', 20, true),
(gen_random_uuid(), 'dare', 'Imitate every person in the room one by one.', 20, true),
(gen_random_uuid(), 'dare', 'Send a genuine compliment to someone you haven''t talked to in months.', 20, true),
(gen_random_uuid(), 'dare', 'Let the group read your notes app out loud.', 20, true),
(gen_random_uuid(), 'dare', 'Narrate everything you do for the next 60 seconds like a nature documentary.', 20, true),
(gen_random_uuid(), 'dare', 'Let the group send one emoji reply to any conversation on your phone.', 20, true),
(gen_random_uuid(), 'dare', 'Do the worm on the floor right now.', 20, true),
(gen_random_uuid(), 'dare', 'Text your most recent contact "you''re actually my favourite person, don''t tell anyone".', 20, true);
