-- ============================================================
-- Seed: 100 Truths + 100 Dares (classroom-friendly, English only)
-- ============================================================

INSERT INTO truth_or_dare (type, content, points) VALUES

-- TRUTHS (50)
('truth', 'What is the most embarrassing thing that has ever happened to you in class?', 10),
('truth', 'Have you ever pretended to be sick just to skip school?', 10),
('truth', 'What is the worst grade you have ever gotten on a test?', 10),
('truth', 'Have you ever cheated on a test or assignment?', 10),
('truth', 'Who in this room do you think would make the best teacher?', 10),
('truth', 'What subject do you secretly hate but pretend to like?', 10),
('truth', 'Have you ever blamed someone else for something you did?', 10),
('truth', 'What is the longest you have gone without showering?', 10),
('truth', 'Have you ever laughed so hard in class that you were asked to leave?', 10),
('truth', 'What is the most childish thing you still do?', 10),
('truth', 'Have you ever fallen asleep during an online class and been caught?', 10),
('truth', 'What is the most embarrassing song on your playlist right now?', 10),
('truth', 'Have you ever had a crush on a teacher?', 10),
('truth', 'What is the biggest lie you have told your parents?', 10),
('truth', 'Have you ever sent a text to the wrong person? What did it say?', 10),
('truth', 'What excuse do you use most often for not doing homework?', 10),
('truth', 'Who do you think is the most annoying person in your batch?', 10),
('truth', 'Have you ever borrowed something and never returned it?', 10),
('truth', 'What is your most embarrassing autocorrect fail?', 10),
('truth', 'Have you ever lied about finishing your assignment?', 10),
('truth', 'What is the most useless thing you have memorized for an exam?', 10),
('truth', 'Have you ever cried because of a movie or show and denied it?', 10),
('truth', 'What is your secret guilty pleasure snack?', 10),
('truth', 'Have you ever walked into the wrong classroom and not realized immediately?', 10),
('truth', 'What is the weirdest thing you have ever Googled?', 10),
('truth', 'Have you ever talked in your sleep?', 10),
('truth', 'What is something you do when no one is watching?', 10),
('truth', 'Have you ever pretended not to hear someone to avoid talking to them?', 10),
('truth', 'What is the most embarrassing nickname you have been given?', 10),
('truth', 'Have you ever accidentally liked an old photo while stalking someone on Instagram?', 10),
('truth', 'What is the pettiest reason you have ever stopped talking to someone?', 10),
('truth', 'Have you ever eaten food that fell on the floor?', 10),
('truth', 'What is a talent you have that no one knows about?', 10),
('truth', 'Have you ever read someone else''s private messages?', 10),
('truth', 'What is the most money you have ever wasted on something completely useless?', 10),
('truth', 'Have you ever faked being busy to avoid hanging out with someone?', 10),
('truth', 'What is the worst haircut you have ever had?', 10),
('truth', 'Have you ever cried during a sports game?', 10),
('truth', 'What is something you are irrationally afraid of?', 10),
('truth', 'Have you ever forgotten someone''s name moments after being introduced?', 10),
('truth', 'What is the most ridiculous argument you have ever had?', 10),
('truth', 'Have you ever danced alone in your room and been caught?', 10),
('truth', 'What is the worst advice you have ever given someone?', 10),
('truth', 'Have you ever skipped brushing your teeth and then talked to someone?', 10),
('truth', 'What is your most embarrassing childhood memory?', 10),
('truth', 'Have you ever pretended to know something you had no clue about?', 10),
('truth', 'What is the laziest thing you do regularly?', 10),
('truth', 'Have you ever been caught talking about someone who was right behind you?', 10),
('truth', 'What is the most desperate thing you have done to get someone to like you?', 10),
('truth', 'What would you do first if you were invisible for a day?', 10),

-- DARES (50)
('dare', 'Do your best impression of the strictest teacher you know.', 20),
('dare', 'Speak only in rhymes for the next two minutes.', 20),
('dare', 'Tell the worst joke you know and keep a straight face.', 20),
('dare', 'Do 20 jumping jacks right now.', 20),
('dare', 'Sing the first verse of the national anthem.', 20),
('dare', 'Text your mom a random animal emoji and show everyone her reply.', 20),
('dare', 'Walk like a penguin around the room for 30 seconds.', 20),
('dare', 'Say the alphabet backwards as fast as you can.', 20),
('dare', 'Do your best runway model walk across the room.', 20),
('dare', 'Make the ugliest face you can and hold it for 10 seconds.', 20),
('dare', 'Call a contact and sing happy birthday to them right now.', 20),
('dare', 'Do a 30-second dramatic movie villain monologue.', 20),
('dare', 'Try to lick your elbow.', 20),
('dare', 'Do your best robot dance for 20 seconds.', 20),
('dare', 'Name 10 vegetables in 10 seconds.', 20),
('dare', 'Talk without closing your mouth properly for the next 60 seconds.', 20),
('dare', 'Pretend to be a sports commentator narrating someone tying their shoelace.', 20),
('dare', 'Do your best impression of a baby learning to walk.', 20),
('dare', 'Speak in slow motion for the next two minutes.', 20),
('dare', 'Let the group change your phone wallpaper for the rest of the day.', 20),
('dare', 'Do 10 pushups right now.', 20),
('dare', 'Recite a full tongue twister three times fast.', 20),
('dare', 'Act out a scene from your favourite movie without using words.', 20),
('dare', 'Pretend you are a news anchor and deliver today''s weather in a dramatic voice.', 20),
('dare', 'Do your best impression of a person from a different country.', 20),
('dare', 'Pretend to interview someone in the room as if they are a celebrity.', 20),
('dare', 'Speak with an accent of your choice for the next 3 minutes.', 20),
('dare', 'Draw a portrait of the person to your left in 60 seconds and show everyone.', 20),
('dare', 'Do your funniest dance move for 30 seconds.', 20),
('dare', 'Attempt to do a split.', 20),
('dare', 'Narrate everything you do for the next 2 minutes in third person.', 20),
('dare', 'Do your best impression of a specific animal for 30 seconds.', 20),
('dare', 'Compliment every person in the room with a specific and creative compliment.', 20),
('dare', 'Do your best impression of a movie trailer narrator.', 20),
('dare', 'Swap your phone with the person next to you for 2 minutes — they can scroll but not post.', 20),
('dare', 'Talk like a pirate for the next 3 minutes.', 20),
('dare', 'Do an imaginary cooking show segment for 60 seconds.', 20),
('dare', 'Pretend you are a statue and stay perfectly still for 30 seconds.', 20),
('dare', 'Make a sound like 5 different animals in a row.', 20),
('dare', 'Describe your morning routine as if it were an Olympic sport.', 20),
('dare', 'Do your best infomercial for a random object near you.', 20),
('dare', 'Hold a plank for 30 seconds.', 20),
('dare', 'Recite the periodic table elements you remember in 30 seconds.', 20),
('dare', 'Act like you are accepting an Oscar for 60 seconds.', 20),
('dare', 'Do a dramatic reading of the last text message you received.', 20),
('dare', 'Invent and perform a handshake with the person next to you right now.', 20),
('dare', 'Talk like a robot who is malfunctioning for 2 minutes.', 20),
('dare', 'Let the group ask your phone assistant one question of their choice.', 20),
('dare', 'Name 5 capitals of countries in 10 seconds.', 20),
('dare', 'Do your best impression of a disappointed parent.', 20);
