-- Seed truth and dare questions
-- Run once after schema creation

INSERT INTO truth_or_dare (id, type, content, points) VALUES
  (gen_random_uuid(), 'truth', 'What is the most embarrassing thing that has happened to you in class?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever pretended to be sick to skip class?', 10),
  (gen_random_uuid(), 'truth', 'Who do you have a crush on in this room?', 10),
  (gen_random_uuid(), 'truth', 'What is the last lie you told?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever cheated on a test?', 10),
  (gen_random_uuid(), 'truth', 'What is the most childish thing you still do?', 10),
  (gen_random_uuid(), 'truth', 'What is your most embarrassing autocorrect fail?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever laughed so hard in class you got in trouble?', 10),
  (gen_random_uuid(), 'truth', 'What subject do you secretly hate but pretend to like?', 10),
  (gen_random_uuid(), 'truth', 'Who do you think is the funniest person in your batch?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever fallen asleep in a lecture?', 10),
  (gen_random_uuid(), 'truth', 'What is something you have done that you thought you would never get caught doing?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever had a crush on a teacher?', 10),
  (gen_random_uuid(), 'truth', 'What is the most embarrassing song on your playlist?', 10),
  (gen_random_uuid(), 'truth', 'What would you do if you found out your best friend was talking about you behind your back?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever borrowed notes and returned them with your own doodles?', 10),
  (gen_random_uuid(), 'truth', 'What is the most useless thing you learned in school?', 10),
  (gen_random_uuid(), 'truth', 'What is your guilty pleasure TV show or YouTube channel?', 10),
  (gen_random_uuid(), 'truth', 'Have you ever sent a message to the wrong person?', 10),
  (gen_random_uuid(), 'truth', 'What excuse do you use most often to not do homework?', 10),
  (gen_random_uuid(), 'dare', 'Do your best impression of the strictest teacher you know.', 20),
  (gen_random_uuid(), 'dare', 'Speak in rhymes for the next 2 minutes.', 20),
  (gen_random_uuid(), 'dare', 'Tell a joke so bad that everyone groans.', 20),
  (gen_random_uuid(), 'dare', 'Do 15 jumping jacks right now.', 20),
  (gen_random_uuid(), 'dare', 'Sing the first verse of your national anthem.', 20),
  (gen_random_uuid(), 'dare', 'Text your mom a random emoji and show everyone her reply.', 20),
  (gen_random_uuid(), 'dare', 'Walk like a penguin around the room for 30 seconds.', 20),
  (gen_random_uuid(), 'dare', 'Say the alphabet backwards as fast as you can.', 20),
  (gen_random_uuid(), 'dare', 'Do your best runway walk across the room.', 20),
  (gen_random_uuid(), 'dare', 'Make a face so ugly everyone looks away.', 20),
  (gen_random_uuid(), 'dare', 'Call someone in your contacts and sing happy birthday to them.', 20),
  (gen_random_uuid(), 'dare', 'Do a dramatic movie villain monologue for 30 seconds.', 20),
  (gen_random_uuid(), 'dare', 'Try to lick your elbow.', 20),
  (gen_random_uuid(), 'dare', 'Do your best robot dance for 20 seconds.', 20),
  (gen_random_uuid(), 'dare', 'Name 10 vegetables in 10 seconds.', 20),
  (gen_random_uuid(), 'dare', 'Talk without closing your mouth for the next 1 minute.', 20),
  (gen_random_uuid(), 'dare', 'Let the group write a temporary fake tattoo phrase on your arm with a pen.', 20),
  (gen_random_uuid(), 'dare', 'Talk in slow motion for the next 2 minutes.', 20),
  (gen_random_uuid(), 'dare', 'Pretend to be a sports commentator narrating someone tying their shoelace.', 20),
  (gen_random_uuid(), 'dare', 'Do your best impression of a baby learning to walk.', 20);
